/**
 * Emit .xsctn text for the solver.
 *
 * The solver's parser (vendor/mmtl/bem/src/nmmtl_parse_xsctn.cpp) is a
 * hand-rolled fgets/strstr/sscanf scanner, so this generator clones the
 * dialect of the shipped fixtures (bem/tests/trap_test.xsctn) exactly:
 *  - one "-attr value" per line, backslash continuation
 *  - conductivity always carries units ("3.0e+07siemens/meter")
 *  - geometry values unitless => defaultLengthUnits applies
 *  - couplingLength is written in METERS (parser convention)
 *  - object names are program-generated; user text never reaches the file
 *    (a name containing e.g. "Rec" or "-width" would confuse strstr).
 */
import type { Stackup, StackupItem } from '../model/types.ts';
import { isConductor } from '../model/types.ts';

const fmt = (v: number): string => {
  if (!Number.isFinite(v)) throw new Error(`non-finite value in stackup: ${v}`);
  return String(v);
};

function itemLines(item: StackupItem, idx: number): string {
  switch (item.kind) {
    case 'GroundPlane':
      return `GroundPlane G${idx} \n`;
    case 'DielectricLayer':
      return (
        `DielectricLayer D${idx}  \\\n` +
        `\t -thickness ${fmt(item.thickness)} \\\n` +
        `\t -lossTangent ${fmt(item.lossTangent)} \\\n` +
        `\t -permittivity ${fmt(item.permittivity)}\n`
      );
    case 'RectangleDielectric':
      return (
        `RectangleDielectric B${idx}  \\\n` +
        `\t -width ${fmt(item.width)} \\\n` +
        `\t -height ${fmt(item.height)} \\\n` +
        `\t -permittivity ${fmt(item.permittivity)} \\\n` +
        `\t -number 1 \\\n` +
        `\t -pitch 0 \\\n` +
        `\t -yOffset ${fmt(item.yOffset)} \\\n` +
        `\t -xOffset ${fmt(item.xOffset)}\n`
      );
    case 'RectangleConductors': {
      const name = item.isGround ? `grFlank${idx}` : `Cond${idx}`;
      return (
        `RectangleConductors ${name}  \\\n` +
        `\t -width ${fmt(item.width)} \\\n` +
        `\t -height ${fmt(item.height)} \\\n` +
        `\t -conductivity ${item.conductivity.toExponential()}siemens/meter \\\n` +
        `\t -number ${item.number} \\\n` +
        `\t -pitch ${fmt(item.pitch)} \\\n` +
        `\t -yOffset ${fmt(item.yOffset)} \\\n` +
        `\t -xOffset ${fmt(item.xOffset)}\n`
      );
    }
    case 'TrapezoidConductors': {
      const name = item.isGround ? `grFlank${idx}` : `Trap${idx}`;
      return (
        `TrapezoidConductors ${name}  \\\n` +
        `\t -topWidth ${fmt(item.topWidth)} \\\n` +
        `\t -bottomWidth ${fmt(item.bottomWidth)} \\\n` +
        `\t -height ${fmt(item.height)} \\\n` +
        `\t -conductivity ${item.conductivity.toExponential()}siemens/meter \\\n` +
        `\t -number ${item.number} \\\n` +
        `\t -pitch ${fmt(item.pitch)} \\\n` +
        `\t -yOffset ${fmt(item.yOffset)} \\\n` +
        `\t -xOffset ${fmt(item.xOffset)}\n`
      );
    }
    case 'CircleConductors': {
      const name = item.isGround ? `grFlank${idx}` : `Circ${idx}`;
      return (
        `CircleConductors ${name}  \\\n` +
        `\t -diameter ${fmt(item.diameter)} \\\n` +
        `\t -conductivity ${item.conductivity.toExponential()}siemens/meter \\\n` +
        `\t -number ${item.number} \\\n` +
        `\t -pitch ${fmt(item.pitch)} \\\n` +
        `\t -yOffset ${fmt(item.yOffset)} \\\n` +
        `\t -xOffset ${fmt(item.xOffset)}\n`
      );
    }
  }
}

export function generateXsctn(s: Stackup): string {
  const head =
    `#----------------------------------\n` +
    `# Generated by tnt-web\n` +
    `#----------------------------------\n\n` +
    `package require csdl\n\n` +
    `set _title "tnt-web"\n` +
    `set ::Stackup::couplingLength "${s.couplingLengthM}"\n` +
    `set ::Stackup::riseTime "${s.riseTimePs}"\n` +
    `set ::Stackup::frequency "1e9"\n` +
    `set ::Stackup::defaultLengthUnits "${s.units}"\n` +
    `set CSEG ${s.cseg}\n` +
    `set DSEG ${s.dseg}\n\n`;

  const body = s.items.map((item, i) => itemLines(item, i + 1)).join('');
  return head + body;
}

/** Basic validity checks mirroring solver requirements; returns error strings. */
export function validateStackup(s: Stackup): string[] {
  const errs: string[] = [];
  const grounds = s.items.filter((i) => i.kind === 'GroundPlane').length;
  const signals = s.items.filter((i) => isConductor(i) && !i.isGround);
  if (grounds < 1) errs.push('The stackup needs a bottom ground plane (solver requirement).');
  if (grounds > 2) errs.push('At most 2 ground planes are supported (bottom and top).');
  if (signals.length === 0) errs.push('Add at least one signal conductor set.');
  if (s.items.length > 0 && s.items[0].kind !== 'GroundPlane')
    errs.push('The first (bottom) item must be a ground plane.');
  const layerCount = s.items.filter((i) => i.kind === 'DielectricLayer').length;
  if (layerCount === 0) errs.push('Add at least one dielectric layer.');
  for (const it of s.items) {
    if (it.kind === 'DielectricLayer' && it.thickness <= 0)
      errs.push('Dielectric thickness must be > 0.');
    if (it.kind === 'RectangleConductors' && (it.width <= 0 || it.height <= 0))
      errs.push('Conductor width/height must be > 0.');
    if (it.kind === 'TrapezoidConductors' && (it.topWidth <= 0 || it.bottomWidth <= 0 || it.height <= 0))
      errs.push('Trapezoid widths/height must be > 0.');
    if (it.kind === 'CircleConductors' && it.diameter <= 0)
      errs.push('Circle diameter must be > 0.');
    if (isConductor(it) && it.number > 1 && it.pitch <= 0)
      errs.push('Conductor sets with number > 1 need a positive pitch.');
  }
  return errs;
}
