// Generated by tests/benchmarks/eta/fit.py. Costs use matrix dimensions / 1000 and seconds.
export const measuredWorkCosts = {
  "conductor": 30.41500662480582,
  "dielectric": 7.40922383772066,
  "overhead": 0.024730000138282776,
  "lu": {
    "serial": 0.25287480344711666,
    "eigen": 0.047956150489370075
  }
};
